[package]
name = "mercado-core"
version = "0.1.0"
edition = "2024"

[dependencies]
encoding_rs = "0.8.35"
encoding_rs_io = "0.1.7"
csv = "1.2.1"
models = { workspace = true }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
