[package]
name = "processar-csv"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.4"
serde = { version = "1.0.228", features = ["derive"] }
encoding_rs = "0.8.35"
encoding_rs_io = "0.1.7"
models = { workspace = true }
mercado-core = { workspace = true }