[package]
name = "models"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
chrono = "0.4.42"
thiserror = "2.0.17" 
csv = "1.4.0"
encoding_rs = "0.8.35"
encoding_rs_io = "0.1.7"
serde_json = "1.0.145"
